# Generated by Django 5.0.6 on 2024-07-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botAdmin', '0003_alter_chatmessage_options_alter_chats_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='promotion',
            new_name='advertise',
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(verbose_name='Caption')),
                ('period', models.PositiveIntegerField()),
                ('ai_caption', models.BooleanField(default=False, verbose_name='AI Generated Caption')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botAdmin.chats', verbose_name='Chat')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='botAdmin.menuitem')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotion',
            },
        ),
    ]
