# Generated by Django 5.0.6 on 2024-07-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botAdmin', '0006_remove_orders_products_orders_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='table',
        ),
    ]
