# Generated by Django 5.0.6 on 2024-07-10 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botAdmin', '0007_remove_orders_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='botAdmin.tablenumber'),
            preserve_default=False,
        ),
    ]
