# Generated by Django 5.0.6 on 2024-07-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botAdmin', '0009_ordertableitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
