# Generated by Django 5.0.6 on 2024-07-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botAdmin', '0010_alter_orderitem_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='botAdmin.tablenumber'),
        ),
    ]
